name: Main Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
        version: latest
    - name: Build
      run: |
        pnpm run ci
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        retention-days: 1
        path: |
          dist/
          *.html
          
  deploy:
    if: github.event_name != 'pull_request'
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download production artifacts
      uses: actions/download-artifact@v4
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: artifact
